# Generated by Django 2.0.5 on 2018-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180828_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
